### ISSUE TITLE
Http Basic Authentication using port :80:80 and giving false positive results

### ISSUE THREAD

**Issue by pradeepjairamani** [viraintel/OWASP-Nettacker#66]
Please Describe the issue or question and share your OS and Python version.
_________________
**OS**: `Linux`

**OS Version**: `Linux Ubuntu`

**Python Version**: `2.7.3`
![screenshot_17](https://user-images.githubusercontent.com/24669027/37253417-875fa558-2557-11e8-92c6-290a36d97a0d.png)

**Comment by shaddygarg** [comment]
I did not consider into the possibililty when the mentioned host doesn't have the authentiation. Thanks for telling me a corner case. I will send a fix soon!! :smile:

**Comment by pradeepjairamani** [comment]
I suggest you should use Owasp-DVWA for testing web modules.

Best Regards
Pradeep Jairamani

**Comment by Ali-Razmjoo** [comment]
Hello,

Thanks for reporting this, I think to give the framework `:80:80` is related to the framework to detect the false `target` since we have a topic related to this module with the bug, I'd close this and open another one regarding the framework target types. let me know if you have any ideas.

Best Regards.
